#!/bin/bash

FTP_SERVER="ftp.example.com"
FTP_USER="your_username"
FTP_PASSWORD="your_password"
REMOTE_DIR="/remote/directory"
LOCAL_DIR="/local/directory"

while true
do
    ftp -n $FTP_SERVER <<END_SCRIPT
    quote USER $FTP_USER
    quote PASS $FTP_PASSWORD
    prompt
    lcd $LOCAL_DIR
    cd $REMOTE_DIR
    mget *
    quit
END_SCRIPT

    sleep 30
done
